config/routes.rb
Rails.application.routes.draw do
  resources :currencies do
    collection { post :import }
  end

  root 'page#index'

end

app/models/currency.rb
class Currency < ActiveRecord::Base
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Currency.create! row.to_hash
      
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]

  def index
    
    @currencies = Currency.all.order("created_at DESC")

  end

  def new
    require 'nokogiri'
    require 'open-uri'

    url = "http://minfin.com.ua/"

    data = Nokogiri::HTML(open(url))
    @bid = data.css('.mf-currency-bid')[1]
    @dollarbid = @bid.text.strip[0]+@bid.text.strip[1]+@bid.text.strip[2]+@bid.text.strip[3]+@bid.text.strip[4]  
    @ask = data.css('.mf-currency-ask')[1]
    @dollarask = @ask.text.strip[0]+@ask.text.strip[1]+@ask.text.strip[2]+@ask.text.strip[3]+@ask.text.strip[4]
    
    @currency = Currency.create(date: Time.now, bid: @dollarbid.gsub(/[,]/, '.'), ask: @dollarask.gsub(/[,]/, '.'))
  end
  
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Currency.import(params[:file])
    redirect_to currencies_path, notice: "Currencies uploaded successfully"
  end

  
  private
    def set_currency
      @currency = Currency.find(params[:id])
    end

    def currency_params
      params.require(:currency).permit(:date, :bid, :ask)
    end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
    require 'nokogiri'
    require 'open-uri'

    url = "http://minfin.com.ua/"

    data = Nokogiri::HTML(open(url))
    @bid = data.css('.mf-currency-bid')[1]
    @dollarbid = @bid.text.strip[0]+@bid.text.strip[1]+@bid.text.strip[2]+@bid.text.strip[3]+@bid.text.strip[4]  
    @ask = data.css('.mf-currency-ask')[1]
    @dollarask = @ask.text.strip[0]+@ask.text.strip[1]+@ask.text.strip[2]+@ask.text.strip[3]+@ask.text.strip[4]
    
    data_table = GoogleVisualr::DataTable.new
    data_table.new_column('date', 'Date')
    data_table.new_column('number', 'Bid')
    data_table.new_column('number', 'Ask')

      
      Currency.order("created_at DESC").limit(15).each do |currency|
        data_table.add_row([currency.date, currency.bid, currency.ask])
      end

    
    

    option = { :width => 750, :height => 280, :title => "Exchange rate for the past 15 days", :legend => 'bottom' }
    @chart = GoogleVisualr::Interactive::LineChart.new(data_table, option)
  end

  def min
    Currency.all.order("created_at DESC").limit(15).each do | currency|

    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/currencies/_form.html.haml
= form_for @currency do |f|
  - if @currency.errors.any?
    #error_explanation
      %h2= "#{pluralize(@currency.errors.count, "error")} prohibited this currency from being saved:"
      %ul
        - @currency.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :bid
    = f.text_field :bid
  .field
    = f.label :ask
    = f.text_field :ask
  .actions
    = f.submit 'Save'

app/views/currencies/edit.html.haml
%h1 Editing currency

= render 'form'

= link_to 'Show', @currency
\|
= link_to 'Back', currencies_path

app/views/currencies/index.html.haml
 
.media
  .media-body
    %table.table.table-hover 
      %thead
        %tr
          %th Date
          %th Bid
          %th Ask
          %th
          %th
          %th

      %tbody
        - @currencies.each do |currency|
          %tr
            %td= currency.date
            %td= currency.bid
            %td= currency.ask
            %td= link_to 'Show', currency
            %td= link_to 'Edit', edit_currency_path(currency)
            %td= link_to 'Destroy', currency, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

%h3 
  Import Currency course
  = form_tag import_currencies_path, multipart: true do
    = file_field_tag :file
    = submit_tag "Upload currencies"
  


= link_to 'Home', root_path

app/views/currencies/new.html.haml
%h1 New currency


= link_to 'Back', currencies_path

app/views/currencies/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @currency.date
%p
  %b Bid:
  = @currency.bid
%p
  %b Ask:
  = @currency.ask

= link_to 'Edit', edit_currency_path(@currency)
\|
= link_to 'Back', currencies_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src='https://www.google.com/jsapi'></script>
  <title>USD Exchange</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Font+Name">
  
</head>
<body>


<%= yield %>

</body>
</html>

app/views/page/index.html.haml
%h3 
  %a{:href => 'http://minfin.com.ua/', :target => '_blank'}= "Exchange rate for USD (black market Ukraine)"
  %br
%h1
  Bid 
  =  @dollarbid  
  Ask
  = @dollarask 

%br
= @min


#chart
= render_chart @chart, 'chart'